### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/.../results.json'

### ISSUE THREAD

**Issue by imomaliev** [asottile/detect-test-pollution#6]
Hi @asottile, thank you for another awesome project!

I am getting this error when running with `--testids-file` option

```
root@01c459141970:/path/to/project# pipenv run detect-test-pollution --failing-test 'project/tests/tests.py::Test::test'      --testids-file './testidsfile.txt'
discovering all tests...
-> pre-discovered 100 tests!
ensuring test passes by itself...
-> OK!
ensuring test fails with test group...
Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/project-Qkx4pV5j/bin/detect-test-pollution", line 8, in <module>
    sys.exit(main())
  File "/root/.local/share/virtualenvs/project-Qkx4pV5j/lib/python3.9/site-packages/detect_test_pollution.py", line 299, in main
    return _bisect(testpath, args.failing_test, testids)
  File "/root/.local/share/virtualenvs/project-Qkx4pV5j/lib/python3.9/site-packages/detect_test_pollution.py", line 224, in _bisect
    if _passed_with_testlist(testpath, failing_test, testids):
  File "/root/.local/share/virtualenvs/project-Qkx4pV5j/lib/python3.9/site-packages/detect_test_pollution.py", line 136, in _passed_with_testlist
    with open(results_json) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmp4c4aahsz/results.json'
```

I will try to make a reproducible example on the weekend. In the meantime I was hoping maybe you have some clues what could be the problem here.

**Comment by asottile** [comment]
no idea without a reproduction. dtp injects a plugin which writes that file

please open a new issue with a reproduction

**Comment by cdce8p** [comment]
I had a similar issue and was able to reproduce it. The error is basically the fallback if something with pytest has gone wrong. Some of my examples
* Test collection failed due to a missing dependency.
* Invalid test-id in `testids` file.

The code currently suppresses **all** errors which include such invalid inputs.
https://github.com/asottile/detect-test-pollution/blob/bc901e084baf356dd4393312c1ef694b8913bd55/detect_test_pollution.py#L126-L132

Maybe it would sense to check the exit code here?
https://docs.pytest.org/en/latest/reference/exit-codes.html

**Comment by imomaliev** [comment]
@cdce8p I didn't find time to mare reproducable example. Maybe you could provide it?

**Comment by cdce8p** [comment]
> @cdce8p I didn't find time to make reproducible example. Maybe you could provide it?

Just add something like this to a test file.
```py
from unknown_module import Unknown
```
It will raise a `ModuleNotFoundError` pytest internally and subsequently result in the `FileNotFoundError`.
